### ISSUE TITLE
Adding extra netconf capabilities

### ISSUE THREAD

**Issue by ugurkaraca3** [PANTHEONtech/lighty-netconf-simulator#110]
Hi guys,

As i understood, lighty netconf simulator is supporting "urn:ietf:params:netconf:base:1.1","urn:ietf:params:netconf:base:1.0","urn:ietf:params:netconf:capability:candidate:1.0" capabilities right now,  do you guys plan to support other capabilities like writable-through-candidate,rollback-on-error,validate,confirmed-commit?
If not, could you share with me some examples to integrate capability into simulator?

Thanks in advance,
Best Regards,
Ugur.

**Comment by ihrasko** [comment]
Thank you for you interest in Lighty.io simulator - your request is scheduled into our support queue.

**Comment by ihrasko** [comment]
We are not planning to implement additional capabilities at the moment. They are not even implemented in OpenDaylight Netconf which is what we are using in simulator.
