### ISSUE TITLE
Multiple Yang Datastore Part Manipulation Bug

### ISSUE THREAD

**Issue by ugurkaraca3** [PANTHEONtech/lighty-netconf-simulator#131]
Hi guys,

I encountered an issue when i try to manipulate multiple datastore part. I created custom yang file and introduced this yang file to simulator then initialized with initial datastore to produce scenario(I also pushed relevant branch to my repository https://github.com/ugurkaraca3/lighty-netconf-simulator/tree/bug/multipleDatastorePartManipulation/ugurkaraca3 you can directly get this branch and try in network-topology-device if you want ).After install successfully, i send netconf request to manipulate datastore(you can find all procedure [allProcedureOutputs.txt](https://github.com/PANTHEONtech/lighty-netconf-simulator/files/10193759/allProcedureOutputs.txt) there). Basically i tried to manipulate 2 different part of datastore and i saw that just one part has manipulated.
It would be perfect if you look at it.

Thanks in advance,
Best Regards,
Ugur.

**Comment by ihrasko** [comment]
We are sorry, simulator supports only one operation per request and its capable updating only top element - in your case `custom-yang-cont`.

https://github.com/PANTHEONtech/lighty-netconf-simulator/blob/master/lighty-netconf-device/README.md

**Comment by ugurkaraca3** [comment]
Ups, If i want to implement it, is it possible guys? Is this functionality restricted from odl? If it is possible, could you share with me some information to implement it?
