### ISSUE TITLE
Issue with Notification producer

### ISSUE THREAD

**Issue by christophebetoule** [PANTHEONtech/lighty-netconf-simulator#132]
Hello !

 I am developing a new netconf node simulator for the  functional tests of the SDN TransportPCE controller developed within the opendaylight community.

So far, the TransportPCE project uses a Honeynode simulator based on the fd.io Honeycomb community (https://gitlab.com/Orange-OpenSource/lfn/odl/honeynode-simulator). Honeynode simulates OpenROADM (and partially Openconfig) devices managed by a NETCONF connector.

As this project is now archived and not maintained, we are developing a new Lightynode simulator based on lighty-netconf-simulator (https://gitlab.com/Orange-OpenSource/lfn/odl/Lightynode-simulator).

But I face an issue with the production of Notification messages from the Lighynode and more precisely with the serializer when the simulator send messages.

Please find below the notifications sent by Lightynode compared with the ones sent by Honeynode :

**Lightynode :**
`<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <eventTime>2022-10-13T11:05:13Z</eventTime>
    <change-notification xmlns="http://org/openroadm/device">
        <change-time>2022-10-13T11:05:13.000065+02:00</change-time>
        <datastore>running</datastore>
        <edit>
            <operation>merge</operation>
            <target>/:org-openroadm-device/:circuit-packs[:circuit-pack-name='2/0']/:ports[:port-name='L1']</target>
        </edit>
    </change-notification>
</notification>`

**Honeynode :**
`<?xml version="1.0" encoding="utf-8"?>
<notification xmlns="urn:ietf:params:netconf:capability:notification:1.0">
  <change-notification xmlns="http://org/openroadm/device">
    <change-time>2022-10-13T11:10:04.000793+02:00</change-time>
    <datastore>running</datastore>
    <edit>
      <target xmlns:a="http://org/openroadm/device">/a:org-openroadm-device/a:circuit-packs[a:circuit-pack-name='2/0']/a:ports[a:port-name='L1']</target>
      <operation>merge</operation>
    </edit>
    <changed-by>
      <server/>
    </changed-by>
  </change-notification>
  <eventTime>2022-10-13T09:10:04.896Z</eventTime>
</notification>`

This issue is that in the "target tag" of Lightynode, the serializer seems not to support the namespace, that produces a failure when trying the deserialize the notification.
I found a serializeData and a serializeRPC in io.lighty.codecs.util.XmlNodeConverter, but nothing specific for serializing notifications.

Thank you very much in advance for your help of how managing notifications with lighty-netconf-simulator.
Best regards,
Christophe

**Comment by dariamaistrenko** [comment]
Hello!

We would be happy to assist to you! 
I can propose you to schedule the zoom call for discussing all the details directly. Here is my email address: Daria.Maistrenko@pantheon.tech. 

Best regards,

Daria Maistrenko
Sales Associate
