### ISSUE TITLE
Where to find the module imported in this file - network-topology-rpcs@2023-09-27.yang

### ISSUE THREAD

**Issue by srinivasev** [PANTHEONtech/lighty-netconf-simulator#234]
Hi Team, 

I see there are import statements in network-topology-rpcs@2023-09-27.yang module . I cannot find these module definitions in this repository. Where to check the same ?

module network-topology-rpcs {

    yang-version 1.1;

    namespace "urn:tech.pantheon.netconfdevice.network.topology.rpcs";
    prefix "ntr";

    **_import network-topology { prefix "nt"; revision-date 2013-10-21; }
    import netconf-node-topology { prefix "nnt"; revision-date 2023-11-21; }
    import odl-netconf-device { prefix "ond"; revision-date 2024-01-20; }_**

**Comment by ihrasko** [comment]
They are coming from our ODL netconf dependency:

- https://github.com/opendaylight/netconf/blob/master/plugins/netconf-client-mdsal/src/test/resources/schemas/network-topology%402013-10-21.yang
- https://github.com/opendaylight/netconf/blob/master/apps/netconf-topology/src/main/yang/netconf-node-topology.yang
- https://github.com/opendaylight/netconf/blob/master/plugins/netconf-client-mdsal/src/main/yang/odl-netconf-device.yang

Best

**Comment by ihrasko** [comment]
To find the correct revision, always check  the netconf repository at release tag revision of version the lighty.io uses. For example, lighty.io 20.1.0 uses netconf 7.0.7 (see: https://github.com/PANTHEONtech/lighty/blob/1bb4beef69a9c45b7a52dbc8b8737240e1032564/lighty-core/dependency-versions/pom.xml).

**Comment by ihrasko** [comment]
Hope that helps, enjoy!
