### ISSUE TITLE
Make asynchronous RPC Calls

### ISSUE THREAD

**Issue by HenningHauser** [PANTHEONtech/lighty-netconf-simulator#235]
Hello,

I would like to make asynchronous RPC calls, so that in the example of the toaster, I can start the process with make-toast and interrupt it with the cancel-toast RPC. Do you have an example for this?

**Comment by ihrasko** [comment]
1) in lighty.io simulator you can implement what you want - even async RPC processing
2) the real support of async operations IMO depends on real NETCONF device you are using

IIRC there is no example for this (and its possible we do not understand each other). Do you have example where you are trying to achieve what you want?
