### ISSUE TITLE
Swagger endpoint for toaster device

### ISSUE THREAD

**Issue by sezerb** [PANTHEONtech/lighty-netconf-simulator#254]
I bring up toaster device and register to lighty-rnc-app successfully. I have two other netconf server instances: one is confD, the other is Yuma. They are also registered to lighty-rnc-app. When I configure and check swagger, I only see rendered RESTCONF end points of confD and Yuma served yang files as mounted NETCONF devices, but not the toaster.

`netconf-console2 -u admin -p admin --port 12345 --get-schema toaster`
This provides toaster schema, hence I expect lighty-rnc-app to render swagger RESTCONF endpoints of toaster simulator device.

P.S. No capability response from toaster simulator device for request  "_restconf/data/network-topology:network-topology?content=nonconfig_" to lighty-rnc-app.

**Comment by ihrasko** [comment]
Hello,

can you share screenshot and result of `GET <RESTCONF>/data/network-topology:network-topology/topology=topology-netconf`?

Thanks!

**Comment by sezerb** [comment]
Hello @ihrasko ,

![toplogy-netconf](https://github.com/user-attachments/assets/8597e90f-270c-4dfc-9307-051300a116a9)

The full response is attached.

[topology-netconf.txt](https://github.com/user-attachments/files/17518016/topology-netconf.txt)

Thanks in advance.

**Comment by ihrasko** [comment]
OK, there is no issue with Swagger, `toaster` device is just not connected - nothing to show in swagger.

You can check logs from lighty.io RNC app and simulator to see what is happening - why `toaster` device is not connected. 

Enjoy debugging :)

**Comment by ihrasko** [comment]
OK
