### ISSUE TITLE
How to get started ?

### ISSUE THREAD

**Issue by v19981999** [PANTHEONtech/lighty-netconf-simulator#73]
Hello,

I'm new to software development and NETCONF. I wanted to start using your Netconf simulator.
How do I get started to use it ? What steps should I take in the Java Eclipse IDE to launch the simulator ?

Any advice and guide will be helpful. Thank you

**Comment by ihrasko** [comment]
Hi,

You can start for example here: https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/master/examples/devices/lighty-toaster-device
