### ISSUE TITLE
lighty-toaster-device SSH shell is not responding to input

### ISSUE THREAD

**Issue by smamusa** [PANTHEONtech/lighty-netconf-simulator#74]
The device simulator starts the device properly and it's possible to connect to it via SSH subsystem, but the shell doesn't respond to input, sending CRLF (I'm a Windows user) does nothing, creates a new line in the shell as any other typed characters and just stays that way. I can't send any of the implemented commands there. 

Here you can see the device being started on port 11950
![image](https://user-images.githubusercontent.com/49687548/145824499-076565ca-fdaa-4c8a-94e7-a797e5866315.png)

But this is the other end
![image](https://user-images.githubusercontent.com/49687548/145824637-b8952617-7a75-40fd-9deb-28ce6aa2b4fe.png)

Is there some unknown cross-platform compatibility issue or...? Perhaps it wasn't test on Windows, should I try testing this within a WSL distro?

**Comment by ihrasko** [comment]
Hi,

get
get-config
are not the correct commands, please use one from the examples: https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/master/examples/devices/lighty-toaster-device

For example:
```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <get/>
</rpc>
]]>]]>
```
