### ISSUE TITLE
Lighty netconf device library can be used in production?

### ISSUE THREAD

**Issue by MuhendisBey** [PANTHEONtech/lighty-netconf-simulator#82]
Hello guys,

to be honest, i can't find a good place to write this question, so that i wrote it here.

What do you think, Is "lighty-netconf-device library" good option to choose it as a netconf server?
As far as I understood, lighty-netconf-device library is acting a netconf server regarding this picture:  
![image](https://user-images.githubusercontent.com/10077290/162380858-0b00e260-5648-4e1b-8149-4450d55c3f83.png)

at the bottom level, there is a "lighty.io NETCONF" and it should be netconf server.

really,  DOes lighty-netconf-device library fit to basis netconf server requirement such as db (running, candidate...), rollback mechanism (on error), validation callback, yang validation and so on.

Many Thanks in advance,
With My Best Regards,
Onur.

**Comment by mmiklus** [comment]
lighty / OpenDaylight can be used as a NETCONF server. For inspiration, please see FD.io Honeycomb project.
