### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by SavashSyuleyman** [PANTHEONtech/lighty-netconf-simulator#83]
after successfull maven build i get this error when i try to run the jar file 

`no main manifest attribute, in lighty-netconf-device-15.2.1-SNAPSHOT.jar`

my machine: 

``` bash
root@playground:[target]:# java --version
java 11 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
root@playground:[target]:#
```

**Comment by PeterSuna** [comment]
Hello SavashSyuleyman,
I assume that you are trying to start lighty-netconf-device library without Main class. You can try one of our prepared example applications:
https://github.com/PANTHEONtech/lighty-netconf-simulator/tree/master/examples/devices

I hope this helps.

**Comment by SavashSyuleyman** [comment]
Im not familiar with Java , thats why i couldnt figure out the problem 😕  thank you
________________________________

**Comment by SavashSyuleyman** [comment]
Im not familiar with Java , thats why i couldnt figure out the problem 😕  thank you
